-- AlterTable
ALTER TABLE "WebNews" ADD COLUMN "core1" TEXT;
ALTER TABLE "WebNews" ADD COLUMN "core2" TEXT;
ALTER TABLE "WebNews" ADD COLUMN "core3" TEXT;
ALTER TABLE "WebNews" ADD COLUMN "core4" TEXT;
ALTER TABLE "WebNews" ADD COLUMN "core5" TEXT;
ALTER TABLE "WebNews" ADD COLUMN "core6" TEXT;
ALTER TABLE "WebNews" ADD COLUMN "core7" TEXT;
