import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { Nav, NavLink } from '@/components/nav'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'WebNews',
  description: 'WebNews with NextJS, generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang='en'>
        <body className={cn('bg-background min-h-screen font-sans antialiased', inter.variable)}>
          {/* <Nav>
            <NavLink href='/'>Home</NavLink>
            <NavLink href='/my-orders'>My Orders</NavLink>
            <NavLink href='/login'>Login</NavLink>
            <NavLink href='/admin'>Admin</NavLink>
            <NavLink href='/logging/log'>Log</NavLink>
            <NavLink href='/logging/clearlog'>ClearLog</NavLink>
          </Nav> */}
          {children}
        </body>
      </html>
    </>
  )
}
